Script started on Tue 02 Feb 2021 03:58:27 PM CST
[?1034hbash-4.2$ cd ~cs[K[K/cs161/root/
bash-4.2$ .sys161 k[K[K[K[K[K[K[K[K/sys161 kernel
sys161: System/161 release 1.14, compiled Feb  2 2021 10:38:15

OS/161 base system version 1.10
Copyright (c) 2000, 2001, 2002, 2003
   President and Fellows of Harvard College.  All rights reserved.

Put-your-group-name-here's system version 0 (ASST0 #2)

Cpu is MIPS r2000/r3000
1872k physical memory available
Device probe...
lamebus0 (system main bus)
emu0 at lamebus0
ltrace0 at lamebus0
ltimer0 at lamebus0
hardclock on ltimer0 (100 hz)
beep0 at ltimer0
rtclock0 at ltimer0
lrandom0 at lamebus0
random0 at lrandom0
lser0 at lamebus0
con0 at lser0
pseudorand0 (virtual)

OS/161 kernel [? for menu]: p /sbin/poweroff
Operation took 0.000162800 seconds
OS/161 kernel [? for menu]: Shutting down.
The system is halted.
sys161: 287936745 cycles (4094474k, 18u, 283842253i)
sys161: 1787 irqs 6 exns 0r/0w disk 17r/658w console 8r/0w/3m emufs 0r/0w net
sys161: Elapsed real time: 11.516647 seconds (25.0018 mhz)
sys161: Elapsed virtual time: 11.517469800 seconds (25 mhz)
bash-4.2$ exit
exit

Script done on Tue 02 Feb 2021 03:59:01 PM CST
